###
POST http://localhost:9000/api/users HTTP/1.1
Content-Type: application/json

{
    "name":"Pepe",
    "age": 50,
    "email": "pepe@gmail.com"
}

###
GET http://localhost:9000/api/users HTTP/1.1


###
GET http://localhost:9000/api/users/6320de2d49c36e165897c8e1 HTTP/1.1

###
PUT http://localhost:9000/api/users/6320de2d49c36e165897c8e1 HTTP/1.1
Content-Type: application/json

{
    "name":"Elvia",
    "age": 50,
    "email": "elvia@gmail.com"
}

###
DELETE  http://localhost:9000/api/users/6320e0a1ca76133185590389 HTTP/1.1
